### ISSUE TITLE
Quesion on cc65

### ISSUE THREAD

**Issue by marianol** [sharpninja/esp32_c64_keyboard#1]
Sorry to create an issue here for this, but picked your most active repo. Looks like you deleted your repo for the your cc65 for 6502/65816 machines VSCode extension https://github.com/sharpninja/vscode-cc65. 
One of the last updates of VS code deprecated 'ms-vscode-csharp ' extension.
The extension is very useful and popular (10K installs), I have no exoerience with VSCode extensions but if you have it happy to give it a go in fixing the dependency.
Thanks!

**Comment by sharpninja** [comment]
I no longer have the code, sorry.

**Comment by marianol** [comment]
Okay, thanks for the reply!. Will try to find another one, yours it was a very nice extension.
